### ISSUE TITLE
Function execution resulted in an error log: UnhandledPromiseRejectionWarning: Unhandled promise rejection: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by addshore** [addshore/twilio-boaty#1]
Keep getting fallbacks to the default message

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection: TypeError: Cannot read property '1' of null
    at inreachDataFromLink (/var/task/handlers/ZN4084504277fd27f763d3001cb9f4aced.js:259:75)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.work (/var/task/handlers/ZN4084504277fd27f763d3001cb9f4aced.js:52:19)
    at async Object.exports.innerHandler (/var/task/handlers/ZN4084504277fd27f763d3001cb9f4aced.js:16:22)
    at async Object.exports.handler (/var/task/handlers/ZN4084504277fd27f763d3001cb9f4aced.js:6:18)
```

Content was `Openweather wind 10 inreachlink.com/LE3ZWRJ`

**Comment by addshore** [comment]
Seems to work just fine running it locally...

```
1/
DATEHOUR: WIND(GUST),DIR(DEG) knots
Oct 9
10:34: 15(18)N(21)
11:00: 15(18)N(21)
12:00: 16(19)N(18)
13:00: 15(19)N(16)
14:00: 15(18)N(18)
2/
15:00: 14(17)NE(24)
16:00: 13(17)N(22)
17:00: 14(17)N(12)
18:00: 14(17)N(16)
19:00: 13(16)N(16)
```
